# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chat-mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'StompClientLib'


  # Pods for chat-mobile

  target 'chat-mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chat-mobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
